application: hlhomestay
version: 1
runtime: python
api_version: 1


handlers:
- url: /
  script: homestay/month_calendar.py

- url: /homestays?/.*
  script: homestay/handler.py

- url: /admin/.*
  script: admin/handler.py
  login: admin

#- url: /session/.*
#  script: session.py

#handlers:
#- url: /static
#  static_dir: static

#- url: /.*
#  script: main.py

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 )$
