application: hlhomestay
version: 1
runtime: python
api_version: 1

handlers:

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /sys.*
  script: sys/handler.py
  login: admin

- url: /admin.*
  script: admin/handler.py
  login: required

- url: /\w+(/\d+)?
  script: client/handler.py

- url: /period_books.*
  script: client/handler.py

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 )$
