application: hlhomestay
version: 1
runtime: python
api_version: 1

handlers:

- url: /homestays(/\w*)?
  script: homestay/handler.py
  login: admin

# must specified homestay's key
- url: /homestays/\w+/rooms/\w*
  script: room/handler.py
  login: admin

- url: /rooms/\w*(/\w*)?
  script: room/handler.py
  login: admin

- url: /rooms/\w+/reservations/\w*
  script: reservation/handler.py

- url: /css
  static_dir: css

- url: /admin/.*
  script: admin/handler.py
  login: required

- url: /\w+(/\d+)?
  script: client/handler.py

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 )$
