application: structedtext
version: 1
runtime: python
api_version: 1
handlers:
- url: /net
  static_dir: net
- url: /db
  static_dir: db
- url: /db_slides
  static_dir: db_slides
- url: /ds
  static_dir: ds
- url: /csec
  static_dir: csec
- url: /hltb
  static_dir: hltb
- url: /css
  static_dir: css
- url: /
  static_files: index.html
  upload: index.html
- url: /sqls
  script: run_rest.py
- url: /food
  static_dir: food
- url: /novel
  static_dir: novel
- url: /taichi
  static_dir: taichi

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (hltb\.*)|
 (hltb\video\.*)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 )$
