application: structedtext
version: 1
runtime: python
api_version: 1
handlers:
- url: /db
  static_dir: db
- url: /css
  static_dir: css
- url: /
  static_files: index.html
  upload: index.html

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 )$
